# Generated by Django 4.0.7 on 2022-08-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJECT_TEAM_NAME', models.CharField(max_length=150)),
                ('CHANGE_IN_PROJECT_SCOPE', models.CharField(max_length=150, unique=True)),
                ('COMMUNICATION_BREAKDOWN', models.CharField(max_length=150)),
                ('INADEQUATE', models.CharField(max_length=150, null=True)),
                ('PLANNING', models.CharField(max_length=150, null=True)),
                ('TEAM_MEMBER_PROCASTINATION', models.CharField(max_length=150, null=True)),
                ('CLIENT_CHANGES_IN_PROJECT', models.CharField(max_length=150, null=True)),
                ('EXTERNAL_CHANGES', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('phonenumber', models.PositiveBigIntegerField(null=True)),
                ('gender', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_r1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_team_head', models.CharField(max_length=150)),
                ('project_team_email', models.CharField(max_length=150, unique=True)),
                ('android', models.CharField(max_length=150)),
                ('frontend', models.CharField(max_length=150, null=True)),
                ('total_team_members1', models.CharField(max_length=150, null=True)),
                ('backend', models.CharField(max_length=150, null=True)),
                ('others', models.CharField(max_length=150, null=True)),
                ('total_team_members2', models.CharField(max_length=150, null=True)),
                ('testing', models.CharField(max_length=150, null=True)),
                ('total_team_members3', models.CharField(max_length=150, null=True)),
                ('total_team_members4', models.CharField(max_length=150, null=True)),
                ('total_team_members5', models.CharField(max_length=150, null=True)),
                ('project_enquiry', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
