# Generated by Django 4.0.2 on 2022-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_teamapp', '0008_project_r1_delete_project_r2'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_file',
            name='solutions',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
