# Generated by Django 4.0.7 on 2022-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_detail_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('contact', models.PositiveBigIntegerField(null=True)),
                ('organisation', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(max_length=150, null=True)),
                ('dob', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('files', models.ImageField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='client_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('phonenumber', models.PositiveBigIntegerField(null=True)),
                ('gender', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='client_project_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=150, null=True)),
                ('organisation_address', models.CharField(max_length=150, unique=True)),
                ('organisation_Email', models.EmailField(max_length=150, unique=True)),
                ('phonenumber', models.PositiveBigIntegerField(null=True)),
                ('services', models.CharField(max_length=150, null=True)),
                ('p_enquiry', models.CharField(max_length=150, null=True)),
                ('p_document', models.ImageField(upload_to='documents')),
                ('approve', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
            ],
        ),
    ]
