# Generated by Django 4.0.7 on 2022-08-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_project_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=150, null=True)),
                ('organisation_address', models.CharField(max_length=150, unique=True)),
                ('organisation_Email', models.EmailField(max_length=150, unique=True)),
                ('phonenumber', models.PositiveBigIntegerField(null=True)),
                ('services', models.CharField(max_length=150, null=True)),
                ('p_enquiry', models.CharField(max_length=150, null=True)),
                ('p_document', models.ImageField(upload_to='documents')),
                ('approve', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='client_project_model',
        ),
    ]
