# Generated by Django 4.0.2 on 2022-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_client_project_models_delete_client_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_model',
            name='actions',
            field=models.BooleanField(default=False),
        ),
    ]
