# Generated by Django 4.0.2 on 2022-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_client_model_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_detail_model',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
