# Generated by Django 4.0.7 on 2022-08-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_teamapp', '0002_technical_team_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_team_details',
            name='current_project_details',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
