# Generated by Django 4.0.7 on 2022-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='technical_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('phonenumber', models.PositiveBigIntegerField(null=True)),
                ('gender', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
