# Generated by Django 4.0.7 on 2022-08-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_teamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='technical_team_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicalteam_head_name', models.CharField(max_length=150)),
                ('technicalteam_email', models.EmailField(max_length=150, unique=True)),
                ('no_of_project_completed', models.CharField(max_length=150)),
                ('current_project_details', models.PositiveBigIntegerField(null=True)),
                ('no_of_workers', models.CharField(max_length=150, null=True)),
                ('experienced', models.CharField(max_length=150, null=True)),
                ('freshers', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
