# Generated by Django 4.0.7 on 2022-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_details_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=150)),
                ('client_organisation_name', models.EmailField(max_length=150, unique=True)),
                ('projectstatus', models.CharField(max_length=150)),
                ('project_completion', models.PositiveBigIntegerField(null=True)),
                ('payment_details', models.FileField(upload_to='payfiles')),
            ],
        ),
    ]
