# Generated by Django 4.0.2 on 2022-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details_send',
            name='organisation_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
