# Generated by Django 4.0.2 on 2022-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_client_details_send_organisation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details_send',
            name='project_completion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
